export const varietals = [
   'Ancelotta',
   'Assamblage',
   'Blanc de Malbecs',
   'Blanco Dulce',
   'Blend',
   'Blend de Blancas',
   'Blend de Malbecs',
   'Blend de Tintos',
   'Blend (Cabernet Franc - Cabernet Sauvignon - Petit Verdot)',
   'Blend (Cabernet Franc - Malbec - Merlot)',
   'Blend (Cabernet Sauvignon - Cabernet Franc)',
   'Blend (Malbec - Cabernet)',
   'Blend (Malbec - Cabernet Franc)',
   'Blend (Malbec - Cabernet Sauvignon - Petit Verdot)',
   'Blend (Malbec - Cabernet Sauvignon - Petit Verdot - Cabernet Franc)',
   'Blend (Malbec - Merlot)',
   'Blend (Malbec - Syrah)',
   'Blend (Malbec - Tannat)',
   'Blend (Merlot - Cabernet Sauvignon)',
   'Blend (Moscatel - Torrontés)',
   'Bonarda',
   'Cabernet',
   'Cabernet Franc',
   'Cabernet Sauvignon',
   'Camporotondo',
   'Carmenere',
   'Chardonnay',
   'Chenin Dulce',
   'Corte',
   'Corte Tinto',
   'Dulce Natural',
   'Gewürztraminer',
   'Gran Assemblage',
   'Gran Cabernet Franc',
   'Gran Corte',
   'Gran Malbec',
   'Malbec',
   'Malbec Rosé',
   'Merlot',
   'Naranjo',
   'Pedro Ximénez',
   'Petit Verdot',
   'Pinot Grigio',
   'Pinot Noir',
   'Red Blend',
   'Rosado',
   'Rosado Blend',
   'Rosado Cofermentado',
   'Rosé',
   'Sangiovese',
   'Sauvignon Blanc',
   'Semillón',
   'Syrah',
   'Tannat',
   'Tempranillo',
   'Tinto',
   'Tinto de Corte',
   'Torrontés',
   'Torrontés Dulce Natural',
   'Torrontés Tardío',
   'Viognier',
   'Viognier Dulce',
]

export const redVarietals = [
   'Ancelotta',
   'Bonarda',
   'Cabernet',
   'Camporotondo',
   'Carmenere',
   'Malbec',
   'Merlot',
   'Petit Verdot',
   'Pinot Noir',
   'Red',
   'Sangiovese',
   'Syrah',
   'Tannat',
   'Tempranillo',
   'Tinto',
   'Tinto de Corte',
]

export const whiteVarietals = [
   'Blanc',
   'Blanca',
   'Chardonnay',
   'Chenin Dulce',
   'Gewürztraminer',
   'Moscatel',
   'Pedro Ximénez',
   'Pinot Grigio',
   'Semillón',
   'Torrontés',
   'Viognier',
];

export const pinkVarietals = [
   'Rosado',
   'Rosé',
];

export const orangeVarietals = [
   'Naranjo',
];